2023-10-18 01:27:34,137 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:27:34,137 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Configure stats pid to 3581575
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_012734-nld6bjwa/logs/debug.log
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_012734-nld6bjwa/logs/debug-internal.log
2023-10-18 01:27:34,138 INFO    MainThread:3581575 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f535786bf40>
2023-10-18 01:27:34,139 INFO    MainThread:3581575 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:27:34,139 INFO    MainThread:3581575 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:27:34,139 INFO    MainThread:3581575 [wandb_init.py:init():618] starting backend
2023-10-18 01:27:34,139 INFO    MainThread:3581575 [wandb_init.py:init():622] setting up manager
2023-10-18 01:27:34,142 INFO    MainThread:3581575 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 01:27:34,144 INFO    MainThread:3581575 [wandb_init.py:init():628] backend started and connected
2023-10-18 01:27:34,158 INFO    MainThread:3581575 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 01:27:34,159 INFO    MainThread:3581575 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 01:27:34,159 INFO    MainThread:3581575 [wandb_init.py:init():720] updated telemetry
2023-10-18 01:27:34,161 INFO    MainThread:3581575 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 01:29:04,253 ERROR   MainThread:3581575 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-18 01:29:06,261 ERROR   MainThread:3581575 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
