2023-10-18 01:03:14,836 INFO    StreamThr :3106015 [internal.py:wandb_internal():86] W&B internal server running at pid: 3106015, started at: 2023-10-18 01:03:14.835706
2023-10-18 01:03:14,839 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status
2023-10-18 01:03:14,846 INFO    WriterThread:3106015 [datastore.py:open_for_write():85] open: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/run-9cm8qp9l.wandb
2023-10-18 01:03:14,847 DEBUG   SenderThread:3106015 [sender.py:send():380] send: header
2023-10-18 01:03:14,848 DEBUG   SenderThread:3106015 [sender.py:send():380] send: run
2023-10-18 01:03:19,856 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: keepalive
2023-10-18 01:03:20,389 INFO    SenderThread:3106015 [dir_watcher.py:__init__():211] watching files in: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files
2023-10-18 01:03:20,389 INFO    SenderThread:3106015 [sender.py:_start_run_threads():1122] run started: 9cm8qp9l with start time 1697590994.834667
2023-10-18 01:03:20,390 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status_report
2023-10-18 01:03:20,411 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: check_version
2023-10-18 01:03:20,411 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: check_version
2023-10-18 01:03:25,412 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: keepalive
2023-10-18 01:03:25,413 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status_report
2023-10-18 01:03:25,466 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: run_start
2023-10-18 01:03:25,467 DEBUG   HandlerThread:3106015 [system_info.py:__init__():32] System info init
2023-10-18 01:03:25,467 DEBUG   HandlerThread:3106015 [system_info.py:__init__():47] System info init done
2023-10-18 01:03:25,467 INFO    HandlerThread:3106015 [system_monitor.py:start():194] Starting system monitor
2023-10-18 01:03:25,468 INFO    SystemMonitor:3106015 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-10-18 01:03:25,468 INFO    HandlerThread:3106015 [system_monitor.py:probe():214] Collecting system info
2023-10-18 01:03:25,469 INFO    SystemMonitor:3106015 [interfaces.py:start():190] Started cpu monitoring
2023-10-18 01:03:25,470 INFO    SystemMonitor:3106015 [interfaces.py:start():190] Started disk monitoring
2023-10-18 01:03:25,471 INFO    SystemMonitor:3106015 [interfaces.py:start():190] Started gpu monitoring
2023-10-18 01:03:25,473 INFO    SystemMonitor:3106015 [interfaces.py:start():190] Started memory monitoring
2023-10-18 01:03:25,475 INFO    SystemMonitor:3106015 [interfaces.py:start():190] Started network monitoring
2023-10-18 01:03:25,532 DEBUG   HandlerThread:3106015 [system_info.py:probe():196] Probing system
2023-10-18 01:03:25,532 DEBUG   HandlerThread:3106015 [gitlib.py:_init_repo():53] git repository is invalid
2023-10-18 01:03:25,532 DEBUG   HandlerThread:3106015 [system_info.py:probe():244] Probing system done
2023-10-18 01:03:25,533 DEBUG   HandlerThread:3106015 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-83-generic-x86_64-with-glibc2.27', 'python': '3.10.8', 'heartbeatAt': '2023-10-18T01:03:25.532604', 'startedAt': '2023-10-18T01:02:57.107463', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'host': '173c51123077', 'username': 'root', 'executable': '/opt/conda/bin/python', 'cpu_count': 32, 'cpu_count_logical': 64, 'cpu_freq': {'current': 2.873437500000003, 'min': 1200.0, 'max': 3900.0}, 'cpu_freq_per_core': [{'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 1.342, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.15, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}, {'current': 2.9, 'min': 1200.0, 'max': 3900.0}], 'disk': {'/': {'total': 459.6391830444336, 'used': 65.89636993408203}}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 251.50527954101562}}
2023-10-18 01:03:25,533 INFO    HandlerThread:3106015 [system_monitor.py:probe():224] Finished collecting system info
2023-10-18 01:03:25,533 INFO    HandlerThread:3106015 [system_monitor.py:probe():227] Publishing system info
2023-10-18 01:03:25,533 DEBUG   HandlerThread:3106015 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-10-18 01:03:25,533 DEBUG   HandlerThread:3106015 [system_info.py:_save_pip():68] Saving pip packages done
2023-10-18 01:03:25,533 DEBUG   HandlerThread:3106015 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-10-18 01:03:26,394 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_created():271] file/dir created: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/requirements.txt
2023-10-18 01:03:26,394 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_created():271] file/dir created: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/conda-environment.yaml
2023-10-18 01:03:29,066 DEBUG   HandlerThread:3106015 [system_info.py:_save_conda():87] Saving conda packages done
2023-10-18 01:03:29,068 INFO    HandlerThread:3106015 [system_monitor.py:probe():229] Finished publishing system info
2023-10-18 01:03:29,069 DEBUG   SenderThread:3106015 [sender.py:send():380] send: files
2023-10-18 01:03:29,069 INFO    SenderThread:3106015 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-10-18 01:03:29,091 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: stop_status
2023-10-18 01:03:29,092 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: stop_status
2023-10-18 01:03:29,095 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: internal_messages
2023-10-18 01:03:29,393 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_modified():288] file/dir modified: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/conda-environment.yaml
2023-10-18 01:03:29,393 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_created():271] file/dir created: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/wandb-metadata.json
2023-10-18 01:03:34,452 DEBUG   SenderThread:3106015 [sender.py:send():380] send: telemetry
2023-10-18 01:03:34,453 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status_report
2023-10-18 01:03:34,993 INFO    wandb-upload_0:3106015 [upload_job.py:push():131] Uploaded file /tmp/tmprqtu82aywandb/b52zqcij-wandb-metadata.json
2023-10-18 01:03:35,396 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_created():271] file/dir created: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/output.log
2023-10-18 01:03:37,397 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_modified():288] file/dir modified: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/output.log
2023-10-18 01:03:39,463 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status_report
2023-10-18 01:03:44,091 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: stop_status
2023-10-18 01:03:44,092 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: keepalive
2023-10-18 01:03:44,092 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: internal_messages
2023-10-18 01:03:44,092 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: stop_status
2023-10-18 01:03:44,500 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status_report
2023-10-18 01:03:44,700 DEBUG   SenderThread:3106015 [sender.py:send():380] send: telemetry
2023-10-18 01:03:44,701 DEBUG   SenderThread:3106015 [sender.py:send():380] send: exit
2023-10-18 01:03:44,702 INFO    SenderThread:3106015 [sender.py:send_exit():585] handling exit code: 0
2023-10-18 01:03:44,702 INFO    SenderThread:3106015 [sender.py:send_exit():587] handling runtime: 19
2023-10-18 01:03:44,704 INFO    SenderThread:3106015 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-10-18 01:03:44,705 INFO    SenderThread:3106015 [sender.py:send_exit():593] send defer
2023-10-18 01:03:44,705 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,706 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 0
2023-10-18 01:03:44,706 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,706 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 0
2023-10-18 01:03:44,706 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 1
2023-10-18 01:03:44,707 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,707 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 1
2023-10-18 01:03:44,707 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,707 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 1
2023-10-18 01:03:44,707 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 2
2023-10-18 01:03:44,708 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,708 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 2
2023-10-18 01:03:44,708 INFO    HandlerThread:3106015 [system_monitor.py:finish():203] Stopping system monitor
2023-10-18 01:03:44,708 DEBUG   SystemMonitor:3106015 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2023-10-18 01:03:44,709 INFO    HandlerThread:3106015 [interfaces.py:finish():202] Joined cpu monitor
2023-10-18 01:03:44,709 DEBUG   SystemMonitor:3106015 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2023-10-18 01:03:44,710 INFO    HandlerThread:3106015 [interfaces.py:finish():202] Joined disk monitor
2023-10-18 01:03:44,710 DEBUG   SystemMonitor:3106015 [system_monitor.py:_start():183] Publishing last batch of metrics
2023-10-18 01:03:44,749 INFO    HandlerThread:3106015 [interfaces.py:finish():202] Joined gpu monitor
2023-10-18 01:03:44,749 INFO    HandlerThread:3106015 [interfaces.py:finish():202] Joined memory monitor
2023-10-18 01:03:44,749 INFO    HandlerThread:3106015 [interfaces.py:finish():202] Joined network monitor
2023-10-18 01:03:44,750 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,750 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 2
2023-10-18 01:03:44,751 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 3
2023-10-18 01:03:44,751 DEBUG   SenderThread:3106015 [sender.py:send():380] send: stats
2023-10-18 01:03:44,751 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,752 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 3
2023-10-18 01:03:44,752 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,753 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 3
2023-10-18 01:03:44,753 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 4
2023-10-18 01:03:44,753 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,753 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 4
2023-10-18 01:03:44,754 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,754 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 4
2023-10-18 01:03:44,754 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 5
2023-10-18 01:03:44,754 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,754 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 5
2023-10-18 01:03:44,755 DEBUG   SenderThread:3106015 [sender.py:send():380] send: summary
2023-10-18 01:03:44,755 INFO    SenderThread:3106015 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-10-18 01:03:44,756 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,756 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 5
2023-10-18 01:03:44,756 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 6
2023-10-18 01:03:44,756 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:44,756 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 6
2023-10-18 01:03:44,757 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:44,757 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 6
2023-10-18 01:03:44,762 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: status_report
2023-10-18 01:03:45,012 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 7
2023-10-18 01:03:45,012 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:45,012 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 7
2023-10-18 01:03:45,013 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:45,013 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 7
2023-10-18 01:03:45,401 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_modified():288] file/dir modified: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/config.yaml
2023-10-18 01:03:45,401 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_created():271] file/dir created: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/wandb-summary.json
2023-10-18 01:03:45,703 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:46,504 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 8
2023-10-18 01:03:46,505 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:46,505 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:46,505 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 8
2023-10-18 01:03:46,506 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:46,506 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 8
2023-10-18 01:03:46,506 INFO    SenderThread:3106015 [job_builder.py:build():281] Attempting to build job artifact
2023-10-18 01:03:46,507 INFO    SenderThread:3106015 [job_builder.py:_get_source_type():404] no source found
2023-10-18 01:03:46,507 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 9
2023-10-18 01:03:46,507 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:46,507 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 9
2023-10-18 01:03:46,508 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:46,508 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 9
2023-10-18 01:03:46,508 INFO    SenderThread:3106015 [dir_watcher.py:finish():358] shutting down directory watcher
2023-10-18 01:03:46,704 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:47,402 INFO    Thread-25 :3106015 [dir_watcher.py:_on_file_modified():288] file/dir modified: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/output.log
2023-10-18 01:03:47,403 INFO    SenderThread:3106015 [dir_watcher.py:finish():388] scan: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files
2023-10-18 01:03:47,403 INFO    SenderThread:3106015 [dir_watcher.py:finish():402] scan save: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/wandb-metadata.json wandb-metadata.json
2023-10-18 01:03:47,403 INFO    SenderThread:3106015 [dir_watcher.py:finish():402] scan save: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/conda-environment.yaml conda-environment.yaml
2023-10-18 01:03:47,404 INFO    SenderThread:3106015 [dir_watcher.py:finish():402] scan save: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/output.log output.log
2023-10-18 01:03:47,404 INFO    SenderThread:3106015 [dir_watcher.py:finish():402] scan save: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/wandb-summary.json wandb-summary.json
2023-10-18 01:03:47,409 INFO    SenderThread:3106015 [dir_watcher.py:finish():402] scan save: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/config.yaml config.yaml
2023-10-18 01:03:47,410 INFO    SenderThread:3106015 [dir_watcher.py:finish():402] scan save: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/requirements.txt requirements.txt
2023-10-18 01:03:47,414 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 10
2023-10-18 01:03:47,415 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:47,421 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:47,426 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 10
2023-10-18 01:03:47,430 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:47,430 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 10
2023-10-18 01:03:47,431 INFO    SenderThread:3106015 [file_pusher.py:finish():175] shutting down file pusher
2023-10-18 01:03:47,709 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:47,710 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:48,321 INFO    wandb-upload_0:3106015 [upload_job.py:push():131] Uploaded file /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/conda-environment.yaml
2023-10-18 01:03:48,712 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:48,713 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:49,714 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:49,715 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:50,715 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:50,715 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:51,715 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:51,716 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:52,682 ERROR   wandb-upload_2:3106015 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-18 01:03:52,682 ERROR   wandb-upload_2:3106015 [internal_api.py:execute():370] {"errors":[{"message":"run TCN/9cm8qp9l not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-18 01:03:52,683 ERROR   Thread-24 (_thread_body):3106015 [step_upload.py:_handle_event():200] Failed to upload file: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/wandb-summary.json
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/opt/conda/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-18 01:03:52,686 ERROR   wandb-upload_3:3106015 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-18 01:03:52,693 ERROR   wandb-upload_4:3106015 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-10-18 01:03:52,696 ERROR   wandb-upload_3:3106015 [internal_api.py:execute():370] {"errors":[{"message":"run TCN/9cm8qp9l not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-18 01:03:52,696 ERROR   wandb-upload_4:3106015 [internal_api.py:execute():370] {"errors":[{"message":"run TCN/9cm8qp9l not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-10-18 01:03:52,697 ERROR   Thread-24 (_thread_body):3106015 [step_upload.py:_handle_event():200] Failed to upload file: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/config.yaml
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/opt/conda/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-18 01:03:52,698 ERROR   Thread-24 (_thread_body):3106015 [step_upload.py:_handle_event():200] Failed to upload file: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/requirements.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/opt/conda/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/opt/conda/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-10-18 01:03:52,716 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:52,717 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:53,135 INFO    wandb-upload_1:3106015 [upload_job.py:push():131] Uploaded file /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/files/output.log
2023-10-18 01:03:53,336 INFO    Thread-24 (_thread_body):3106015 [sender.py:transition_state():613] send defer: 11
2023-10-18 01:03:53,337 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:53,337 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 11
2023-10-18 01:03:53,338 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:53,338 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 11
2023-10-18 01:03:53,338 INFO    SenderThread:3106015 [file_pusher.py:join():181] waiting for file pusher
2023-10-18 01:03:53,338 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 12
2023-10-18 01:03:53,338 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:53,339 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 12
2023-10-18 01:03:53,339 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:53,339 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 12
2023-10-18 01:03:53,339 INFO    SenderThread:3106015 [file_stream.py:finish():595] file stream finish called
2023-10-18 01:03:53,528 INFO    SenderThread:3106015 [file_stream.py:finish():599] file stream finish is done
2023-10-18 01:03:53,529 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 13
2023-10-18 01:03:53,529 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:53,529 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 13
2023-10-18 01:03:53,530 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:53,530 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 13
2023-10-18 01:03:53,530 INFO    SenderThread:3106015 [sender.py:transition_state():613] send defer: 14
2023-10-18 01:03:53,531 DEBUG   SenderThread:3106015 [sender.py:send():380] send: final
2023-10-18 01:03:53,531 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: defer
2023-10-18 01:03:53,531 DEBUG   SenderThread:3106015 [sender.py:send():380] send: footer
2023-10-18 01:03:53,531 INFO    HandlerThread:3106015 [handler.py:handle_request_defer():172] handle defer: 14
2023-10-18 01:03:53,532 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: defer
2023-10-18 01:03:53,532 INFO    SenderThread:3106015 [sender.py:send_request_defer():609] handle sender defer: 14
2023-10-18 01:03:53,534 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: internal_messages
2023-10-18 01:03:53,535 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: poll_exit
2023-10-18 01:03:53,535 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: poll_exit
2023-10-18 01:03:53,537 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: server_info
2023-10-18 01:03:53,537 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: get_summary
2023-10-18 01:03:53,537 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: sampled_history
2023-10-18 01:03:53,537 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: server_info
2023-10-18 01:03:53,538 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: job_info
2023-10-18 01:03:53,728 DEBUG   SenderThread:3106015 [sender.py:send_request():407] send_request: job_info
2023-10-18 01:03:53,729 DEBUG   HandlerThread:3106015 [handler.py:handle_request():146] handle_request: shutdown
2023-10-18 01:03:53,730 INFO    HandlerThread:3106015 [handler.py:finish():866] shutting down handler
2023-10-18 01:03:54,543 INFO    WriterThread:3106015 [datastore.py:close():294] close: /workspace/TCN/wandb/run-20231018_010257-9cm8qp9l/run-9cm8qp9l.wandb
2023-10-18 01:03:54,728 INFO    SenderThread:3106015 [sender.py:finish():1534] shutting down sender
2023-10-18 01:03:54,729 INFO    SenderThread:3106015 [file_pusher.py:finish():175] shutting down file pusher
2023-10-18 01:03:54,737 INFO    SenderThread:3106015 [file_pusher.py:join():181] waiting for file pusher
