2023-10-18 01:54:21,325 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:54:21,325 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 01:54:21,325 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:54:21,325 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:54:21,325 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_015421-tuktpzfo/logs/debug.log
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_015421-tuktpzfo/logs/debug-internal.log
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ff221816f80>
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:54:21,326 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: q17kzloe
2023-10-18 01:54:21,328 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/q17kzloe
2023-10-18 01:54:21,328 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 01:54:21,329 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 01:54:21,329 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 01:54:37,750 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 01:54:37,751 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 01:54:37,760 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 01:54:37,778 WARNING MainThread:3583892 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 603, in init
    latest_run.finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 419, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 360, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1925, in finish
    return self._finish(exit_code, quiet)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1957, in _finish
    wandb._sentry.end_session()
  File "/opt/conda/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 43, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 178, in end_session
    client.flush()
  File "/opt/conda/lib/python3.10/site-packages/sentry_sdk/client.py", line 635, in flush
    self.transport.flush(timeout=timeout, callback=callback)
  File "/opt/conda/lib/python3.10/site-packages/sentry_sdk/transport.py", line 526, in flush
    self._worker.flush(timeout, callback)
  File "/opt/conda/lib/python3.10/site-packages/sentry_sdk/worker.py", line 95, in flush
    self._wait_flush(timeout, callback)
  File "/opt/conda/lib/python3.10/site-packages/sentry_sdk/worker.py", line 105, in _wait_flush
    if not self._timed_queue_join(initial_timeout):
  File "/opt/conda/lib/python3.10/site-packages/sentry_sdk/worker.py", line 56, in _timed_queue_join
    queue.all_tasks_done.wait(timeout=delay)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:55:42,533 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_015542-z6atr479/logs/debug.log
2023-10-18 01:55:42,534 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_015542-z6atr479/logs/debug-internal.log
2023-10-18 01:55:42,534 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:55:42,534 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:55:42,534 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 01:55:42,534 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 01:55:42,535 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 01:55:42,536 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 01:55:42,543 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 01:55:42,543 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 01:55:42,543 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 01:55:42,543 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 01:55:48,100 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 01:55:53,103 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 01:55:53,103 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 01:55:56,852 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 01:55:56,852 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 01:55:56,852 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 01:55:56,853 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 01:55:56,853 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:56:22,905 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:56:22,906 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_015622-izf7vc60/logs/debug.log
2023-10-18 01:56:22,906 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_015622-izf7vc60/logs/debug-internal.log
2023-10-18 01:56:22,906 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:56:22,906 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:56:22,906 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: z6atr479
2023-10-18 01:56:22,908 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/z6atr479
2023-10-18 01:56:22,908 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 01:56:22,908 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 01:56:22,909 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 01:56:39,612 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 01:56:39,613 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 01:56:39,623 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 01:56:39,673 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 01:56:39,674 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 01:56:39,677 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 01:56:39,678 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 01:56:39,692 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 01:56:39,692 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 01:56:39,692 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 01:56:39,693 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 01:56:46,164 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 01:56:51,168 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 01:56:51,168 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 01:56:54,910 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 01:56:54,911 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 01:56:54,911 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 01:56:54,911 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 01:56:54,913 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:59:21,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:59:21,736 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_015921-lffuw6ua/logs/debug.log
2023-10-18 01:59:21,736 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_015921-lffuw6ua/logs/debug-internal.log
2023-10-18 01:59:21,736 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:59:21,736 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:59:21,736 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: izf7vc60
2023-10-18 01:59:21,739 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/izf7vc60
2023-10-18 01:59:21,739 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 01:59:21,739 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 01:59:21,739 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 01:59:37,939 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 01:59:37,940 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 01:59:37,950 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 01:59:38,001 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 01:59:38,001 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 01:59:38,004 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 01:59:38,005 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 01:59:38,018 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 01:59:38,019 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 01:59:38,020 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 01:59:38,020 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 01:59:44,525 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 01:59:49,528 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 01:59:49,528 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 01:59:53,296 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 01:59:53,297 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 01:59:53,297 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 01:59:53,297 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 01:59:53,298 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_020641-swou6jo4/logs/debug.log
2023-10-18 02:06:41,019 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_020641-swou6jo4/logs/debug-internal.log
2023-10-18 02:06:41,020 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:06:41,020 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:06:41,020 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: lffuw6ua
2023-10-18 02:06:41,022 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/lffuw6ua
2023-10-18 02:06:41,022 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:06:41,022 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:06:41,022 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:06:56,161 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:06:56,162 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:06:56,172 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:06:56,223 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:06:56,224 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:06:56,226 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:06:56,227 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:06:56,241 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:06:56,241 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:06:56,241 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:06:56,243 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:07:02,768 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:07:07,771 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:07:07,772 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:07:11,574 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:07:11,574 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:07:11,574 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:07:11,574 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:07:11,575 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:12:00,846 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:12:00,846 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:12:00,846 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_021200-x9duq3nv/logs/debug.log
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_021200-x9duq3nv/logs/debug-internal.log
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:12:00,847 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: swou6jo4
2023-10-18 02:12:00,849 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/swou6jo4
2023-10-18 02:12:00,849 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:12:00,850 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:12:00,850 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:12:14,552 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:12:14,553 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:12:14,564 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:12:14,615 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:12:14,615 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:12:14,618 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:12:14,619 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:12:14,633 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:12:14,634 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:12:14,634 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:12:14,635 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:12:21,109 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:12:26,113 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:12:26,113 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:12:29,842 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:12:29,843 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:12:29,843 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:12:29,843 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:12:29,844 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:13:03,101 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_021303-3z4qxg2h/logs/debug.log
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_021303-3z4qxg2h/logs/debug-internal.log
2023-10-18 02:13:03,102 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:13:03,103 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:13:03,103 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: x9duq3nv
2023-10-18 02:13:03,105 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/x9duq3nv
2023-10-18 02:13:03,105 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:13:03,105 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:13:03,105 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:13:18,514 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:13:18,515 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:13:18,526 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:13:18,576 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:13:18,577 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:13:18,580 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:13:18,580 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:13:18,593 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:13:18,594 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:13:18,594 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:13:18,596 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:13:25,127 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:13:30,130 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:13:30,130 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:13:33,854 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:13:33,857 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:13:33,857 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:13:33,857 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:13:33,858 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:26:34,268 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:26:34,268 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_022634-4nf2d0ka/logs/debug.log
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_022634-4nf2d0ka/logs/debug-internal.log
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:26:34,269 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: 3z4qxg2h
2023-10-18 02:26:34,271 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/3z4qxg2h
2023-10-18 02:26:34,271 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:26:34,272 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:26:34,272 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:26:50,429 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:26:50,430 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:26:50,440 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:26:52,449 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:26:52,449 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:26:52,452 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:26:52,453 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:26:52,468 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:26:52,468 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:26:52,468 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:26:52,469 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:26:58,019 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:27:03,022 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:27:03,022 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:27:06,866 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:27:06,866 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:27:06,866 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:27:06,866 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:27:06,867 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:28:06,923 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:28:06,924 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_022806-7ljsklin/logs/debug.log
2023-10-18 02:28:06,924 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_022806-7ljsklin/logs/debug-internal.log
2023-10-18 02:28:06,924 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:28:06,924 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:28:06,924 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: 4nf2d0ka
2023-10-18 02:28:06,926 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/4nf2d0ka
2023-10-18 02:28:06,926 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:28:06,926 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:28:06,926 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:28:23,439 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:28:23,439 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:28:23,445 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:28:23,497 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:28:23,497 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:28:23,500 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:28:23,500 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:28:23,513 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:28:23,513 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:28:23,513 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:28:23,513 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:28:30,016 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:28:35,019 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:28:35,020 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:28:38,751 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:28:38,752 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:28:38,752 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:28:38,752 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:28:38,753 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:32:25,441 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:32:25,442 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_023225-cscyhu4b/logs/debug.log
2023-10-18 02:32:25,442 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_023225-cscyhu4b/logs/debug-internal.log
2023-10-18 02:32:25,442 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:32:25,442 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:32:25,443 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: 7ljsklin
2023-10-18 02:32:25,444 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/7ljsklin
2023-10-18 02:32:25,445 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:32:25,445 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:32:25,445 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:32:39,773 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:32:39,774 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:32:39,784 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:32:39,836 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:32:39,836 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:32:39,839 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:32:39,840 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:32:39,852 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:32:39,853 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:32:39,853 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:32:39,855 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:32:46,336 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:32:51,340 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:32:51,340 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:32:55,069 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:32:55,069 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:32:55,069 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:32:55,069 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:32:55,070 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:36:06,946 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:36:06,946 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:36:06,946 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:36:06,946 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_023606-y25191s4/logs/debug.log
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_023606-y25191s4/logs/debug-internal.log
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:36:06,947 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: cscyhu4b
2023-10-18 02:36:06,949 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/cscyhu4b
2023-10-18 02:36:06,949 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:36:06,950 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:36:06,950 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:36:22,057 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:36:22,058 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:36:22,068 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:36:22,123 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:36:22,124 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:36:22,127 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:36:22,127 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:36:22,141 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:36:22,142 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:36:22,142 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:36:22,144 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:36:28,622 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:36:33,626 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:36:33,626 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:36:37,378 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:36:37,379 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:36:37,379 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:36:37,379 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:36:37,380 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:38:58,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_023858-oywfsukp/logs/debug.log
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_023858-oywfsukp/logs/debug-internal.log
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:38:58,737 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: y25191s4
2023-10-18 02:38:58,738 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/y25191s4
2023-10-18 02:38:58,739 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:38:58,739 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:38:58,739 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:39:14,076 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:39:14,077 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:39:14,088 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:39:14,141 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:39:14,142 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:39:14,145 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:39:14,145 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:39:14,158 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:39:14,158 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:39:14,158 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:39:14,160 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:39:20,641 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:39:25,644 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:39:25,644 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:39:29,334 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:39:29,334 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:39:29,334 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:39:29,335 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:39:29,335 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_024159-my769vss/logs/debug.log
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_024159-my769vss/logs/debug-internal.log
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: oywfsukp
2023-10-18 02:41:59,204 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/oywfsukp
2023-10-18 02:41:59,204 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:41:59,204 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:41:59,205 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:44:19,507 WARNING MsgRouterThr:3583892 [router.py:message_loop():77] message_loop has been closed
2023-10-18 02:44:25,246 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:44:25,246 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:44:25,332 ERROR   MainThread:3583892 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2177, in _atexit_cleanup
    self._on_finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2416, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 603, in init
    latest_run.finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 419, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 360, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1925, in finish
    return self._finish(exit_code, quiet)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1940, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2188, in _atexit_cleanup
    self._backend.cleanup()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 232, in cleanup
    self.interface.join()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 522, in join
    super().join()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 680, in join
    _ = self._communicate_shutdown()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 419, in _communicate_shutdown
    _ = self._communicate(record)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 291, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-10-18 02:44:35,990 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:44:35,990 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_024435-ne4kh9d5/logs/debug.log
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_024435-ne4kh9d5/logs/debug-internal.log
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: oywfsukp
2023-10-18 02:44:35,993 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/oywfsukp
2023-10-18 02:44:36,044 ERROR   MainThread:3583892 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 603, in init
    latest_run.finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 419, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 360, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1925, in finish
    return self._finish(exit_code, quiet)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1953, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 213, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 52, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
